### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by delirehberi** [workouse/popup-sylius#1]
Won't work as expected.

```
TypeError: rules is not iterabletr_TR:604:39
    <anonymous> http://bk.it/tr_TR/:604
```

```javascript
const [successCookieDuration] = rules;
```

Possible solution:
```javascript
//turns rules to an array
let _rules = JSON.parse(popup.getAttribute('data-popup-rules'));
const rules = Object.keys(_rules).map(i => _rules[i]);
```

**Comment by htaoufikallah** [comment]
I just try it it doesn't work for me
In the db it is saved like this: {"workouse_popup_plugin.ui.success_cookie_duration":"successCookieDuration"}
In the the form it is displayed correctly with the translation value not the id
And in the rendered html it is rendered like this: 
<div id="popup" data-popup-id="2" data-popup-rules="{&quot;workouse_popup_plugin.ui.success_cookie_duration&quot;:&quot;successCookieDuration&quot;}"></div>

And here is the js error I get now:
Uncaught TypeError: Invalid attempt to destructure non-iterable instance

Tell me if I'm missing something.
